// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Statement = 3,
  Block = 5,
  Identifier = 7,
  Expression = 9,
  Literal = 10,
  String = 11,
  Number = 12,
  Boolean = 13,
  Lambda = 15,
  Params = 18,
  Range = 20,
  IfExpression = 22,
  ElseBranch = 24,
  MatchExpression = 26,
  MatchArm = 28
