[package]
name = "icelang"
version = "0.1.0"
edition = "2021"
authors = ["LIOKA Ranarison Fiderana"]
keywords = ["scripting-language", "interpreter"]
categories = ["interpreter"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
